name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        # versão lida automaticamente de packageManager no package.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml
            app/pnpm-lock.yaml

      - name: Instalar dependências
        run: pnpm install --recursive --frozen-lockfile

      - name: Build e Deploy (Publica no GH Pages)
        # Este passo só corre se o build e a versão estiverem OK
        working-directory: ./app
        run: |
          pnpm run build
          pnpm run deploy
        env:
          # Injeta o token para o comando 'gh-pages' conseguir fazer push
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
